### PR TITLE
consolidate repositories and rename NPM package to freshdesk-api

### PR DESCRIPTION
**Pull request by maxkoryukov**
**DO NOT MERGE** Actually, this should be an issue, but I want to share my patches along with thoughts

I suggest to merge https://github.com/kumarharsh/node-freshdesk into this, but before we should finish some preparation.

This is my point of view:

### git

1. The `master` branch of this repository is intended for _active_ development. Currently - for **Freshdesk API v2**
1. There should be another one branch `API-v1` in this repository, containing code from https://github.com/kumarharsh/node-freshdesk (as the most mature node-wrapper for Freshdesk APIv1)
    * [x] @arjunkomath should create new branch `API-v1` in this repo
    * [x] ~~@kumarharsh~~  @maxkoryukov should fork this repo
    * [x] ~~@kumarharsh~~  @maxkoryukov should switch to branch `API-v1`, and remove all the existing code
    * [x] ~~@kumarharsh~~  @maxkoryukov move his code to the new branch, commit, push, pull request **DONE** in [**this PR**](https://github.com/maxkoryukov/node-freshdesk-api/tree/upg/API-v1-migrate) will send a PR soon 
    * [x] @maxkoryukov or @kumarharsh or @arjunkomath provide adaptation of new code to guides of this repo :muscle: 
    * [x] @maxkoryukov tune the publishing settings for the version `API-v1` by adding:
      ```json
        "publishConfig": {
          "tag": "APIv1",
          "access": "public"
        }
      ```
1. codebase of `master` and `API-v1` live separately.
1. the name of the repository remains the same `node-freshdesk-api`

### npm
  - [x] :warning: rename package to **`freshdesk-api`** (suffix _node-_ is overkill for NPM packages :muscle: ))
  - [x] publish @kumarharsh 's version of the package from branch `API-v1` of this repository with version `1.0.0` under new name
  - [x] mark published package 1.0.0 as _deprecated_ with message `use version 2.0.0`
  - [x] publish package from `master` branch with version `2.0.0-beta.1`
  - [ ] provide some tests and stuff, to release the stable version `2.0.0`

### other packages/repositories
1. [ ] (**in progress**) @maxkoryukov: send a standard pull request (from template) to other repositories with javascript freshdesk API, pull request should contain:
  * label **DEPRECATED** on the top of `README.md`
  * instructions _How to deprecate package on NPM_ (with publishing new version with deprecation warning in the README)

## why rename

`node-freshdesk-api` -> `freshdesk-api`

* `node-` is an overkill for NPM package. Everybody know, that NPM is for Node (sometimes for browser package, but it is the other question)
* `freshdesk` is required
* prefix `-api` is an indicator, that this is not a freshdesk itself))

May be, the @freshdesk team will fork this repository, in this case this repo will join to the dozens of their repositories;)

## why we should join repositories

I am not finally sure, but it seems, like it will be easier to maintain versioning of the package, when the sources are stored in one repository;)

Hmm.. We could have two separate repositories: [by kumarharsh](https://github.com/kumarharsh/node-freshdesk) and [current](https://github.com/arjunkomath/node-freshdesk-api). **But**! the final target is a package **for users**. I spent 2 hours to choose, which NPM package I should use in production (there are really tons of `*-freshdesk-*` packages). But if this repository will have hundreds of commits, real releases, and will be maintained - the people will know, which NPM package to choose;)

### CODE REVIEW

**Comment by arjunkomath** [comment]
@maxkoryukov @kumarharsh The plans looks good. I've created the new branch API-v1.

**Comment by arjunkomath** [comment]
@maxkoryukov We need to update the docs in master, we haven't included the details of v1 API support.

**Comment by maxkoryukov** [comment]
@arjunkomath , batteries included :ok_hand: already in this PR, in this commit: 682a7f8d64f46ffcc29d170f6d0f26796114aea3

**Comment by maxkoryukov** [comment]
I think, we could merge this PR :thinking: 

The remaining tasks:

* provide tests for requests
* implement the remaining methods

could be solved in separated issues;) I am already use **merged** version (from my fork) in production;)

so, to finish this PR:

* [ ] merge PR
* [ ] update version in `package.json` in master branch to `2.0.0`
* [ ] publish package on NPM


Also, regarding **publishing on NPM**: I think it is possible to drop all `gulp` tasks, because `npm version minor` and `npm version patch` do the same things as existing `gulp` tasks.

So the publishing on NPM could follow this steps:

1. merge PR or add some changes to **this** (origin) repository
  > to apply changes
1. pull changes to local PC
  > to get the recent version of code
1. **locally** run `npm version patch` or `npm version minor`, depending on applied changes
  > to create new tag and increase version in `package.json`
1. **locally** run `git push --follow-tags`
  > to send changes to this repository

and the final step: **Travis CI** will provide _build_ (if necessary, for ex. for cofeescript), testing, linting, and publishing on NPM (automatically)

**Comment by maxkoryukov** [comment]
@arjunkomath , I think, we could merge this PR :thinking: 

The remaining tasks:

* provide tests for requests
* implement the remaining methods

could be solved in separated issues;) I am already use **merged** version (from my fork) in production;)

so, to finish this PR:

* [ ] merge PR
* [ ] update version in `package.json` in master branch to `2.0.0`
* [ ] publish package on NPM


Also, regarding **publishing on NPM**: I think it is possible to drop all `gulp` tasks, because `npm version minor` and `npm version patch` do the same things as existing `gulp` tasks.

So the publishing on NPM could follow this steps:

1. merge PR or add some changes to **this** (origin) repository
    > to apply changes
1. pull changes to local PC
    > to get the recent version of code
1. **locally** run `npm version patch` or `npm version minor`, depending on applied changes
    > to create new tag and increase version in `package.json`
1. **locally** run `git push --follow-tags`
    > to send changes to this repository

and the final step: **Travis CI** will provide _build_ (if necessary, for ex. for cofeescript), testing, linting, and publishing on NPM (automatically)

**Comment by arjunkomath** [comment]
@maxkoryukov Merged.

**Pull request merged**
