### PR TITLE
A lot of improvements

### PR DESCRIPTION
**Pull request by maxkoryukov**
* fixed several bugs:
  * [x] #4 bug with response Statuses
  * [x] #3 dependencies in `package.json`
* methods for working with companies (create, list, update, delete) 
* lint code
* scaffold for tests
* a little documentation

### CODE REVIEW

**Comment by maxkoryukov** [comment]
ping @arjunkomath

**Comment by maxkoryukov** [comment]
@arjunkomath another one thing: the NPM package still **0.0.4**

selection_014


What you think about auto-publishing from Travis CI? I will describe this in separate ticket;)

**Comment by arjunkomath** [comment]
@maxkoryukov That would be great, I just published the latest version.

**Comment by maxkoryukov** [comment]
Ok, I will fix that: #6

**Pull request merged**
