### PR TITLE
Remove GULP and dependencies.

### PR DESCRIPTION
**Pull request by maxkoryukov**
Reason: currently, it is enough to use NPM commands

Just two commands:

1. update version: `npm version patch` (_patch_ is an option, you could pass `major`, `minor`, and `patch`). I am sure, for most cases `patch` will be enough
2. publish changes on github: `git push` (assumed, that local branch is watching appropriate remote branch)

This two commands replaces the content of current `gulpfile`

### CODE REVIEW

**Comment by maxkoryukov** [comment]
I have created PR just for review by @arjunkomath

**Comment by arjunkomath** [comment]
@maxkoryukov Travis will deploy only when a tag is added, I was using gulp to automate adding tags before pushing.

**Comment by maxkoryukov** [comment]
@arjunkomath , the `npm version patch` do the following:

* increase versino in `package.json`
* commit changes
* tag the latest commit

that is why I have removed the Gulp routines: NPM and `git push` - are enough, `gulp` is excessive

**Comment by maxkoryukov** [comment]
@arjunkomath , will you publish new version?

I can do this in a few minutes

**Comment by maxkoryukov** [comment]
It is a **minor** update

**Comment by arjunkomath** [comment]
@maxkoryukov I was not aware npm patch does all that, sorry about that. I won't be publishing manually, let it go through the CI flow.

**Comment by maxkoryukov** [comment]
@arjunkomath , I do the following things:

1. ensure, that current state is stable (since there is no 100% coverage - I just **hope**, that all works fine)
2. run `npm version patch` on my PC
3. run `git push --tags`
4. waiting for results on CI

Hope, this workflow will be suitable for you too;)

**Comment by arjunkomath** [comment]
@maxkoryukov It's fine!

**Pull request merged**
