### PR TITLE
Support filter companies and list all company fields

### PR DESCRIPTION
**Pull request by roniger**
Even though filterCompany is still in beta, adding this support would greatly help out the community

### CODE REVIEW

**Comment by roniger** [comment]
There are currently no tests I could find for the company api
Adding a couple of additional non-covered API calls should not affect the project greatly

**Comment by roniger** [comment]
Almost there :)

**Comment by maxkoryukov** [comment]
@roniger thank you for your contribution!

Please, give me a day or two to review and merge (but it looks good on the first sight)!

**Comment by maxkoryukov** [comment]
@roniger thank you for the contribution!

**Pull request merged**
