### PR TITLE
API v1

### PR DESCRIPTION
**Pull request by maxkoryukov**
Code migrated from the repository of Kumar Harsh (@kumarharsh)

The appropriate version of NPM package is already published:

```shell

npm show freshdesk-api@1.1.1
```

and could be installed as:

```shell

npm install freshdesk-api@APIv1
```

this PR closes almost all items from checklist in arjunkomath/node-freshdesk-api/pull/9

### CODE REVIEW

**Comment by arjunkomath** [comment]
@maxkoryukov @kumarharsh Is the PR ready to be merged?

**Comment by maxkoryukov** [comment]
@arjunkomath  this PR is a copy of original commits to the @kumarharsh 's repository, I have compared the result with original repository (no differences)

After this, I have added files like `.npmignore` , `.editorconfig` and all other, to make codebase similar.

So,the final answer : **YES, this PR is ready to merge**. But don't publish it on NPM;)

The related PR (#9) is very close to be done, almost all issues are solved

**Comment by arjunkomath** [comment]
@maxkoryukov @kumarharsh Merged the PR 👍  Awesome work!

**Comment by kumarharsh** [comment]
@maxkoryukov great work!

**Pull request merged**
